#!/usr/bin/env bash

set -e
set -x

readonly PACKAGE_NAME=bro
readonly SETUP_DIR=/tmp/setup
readonly BRO_DIR=/opt/bro

prepare() {
    echo "preparing package $PACKAGE_NAME"
    mkdir -p "$SETUP_DIR"
    echo "Installing Dependencies"
    apt-get -y install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev
}


#Install the actual package
# https://www.bro.org/sphinx/install/install.html
install() {
    echo "installing package $PACKAGE_NAME"
    cd "$SETUP_DIR"
    git clone --recursive git://git.bro.org/bro
    cd bro
    # We don't want the development version
    # The 2.4 version works in testing.
    git checkout release/2.4
    git submodule update --recursive --init
    # We want to install bro in a known directory
    ./configure --prefix="$BRO_DIR"
    make
    make install
}

#Configure package
setup() {
    echo "configuring package $PACKAGE_NAME"
    # broctl.cfg  configuration
    reduce_logging
    disable_mail

    # networks.cfg configuration
    define_local_networks

    # node.cfg configuration
    # No configuration since it defaults to eth0
    # This will need to be configured if we add Wi-Fi Bridging
}

define_local_networks() {
    # Rewrite the local networks config file
    # 192.168.12.0/24 is the default create_ap local network space.
    echo '192.168.12.0/24      Private IP Space' > "$BRO_DIR/etc/networks.cfg"
}

disable_mail() {
    sed -i 's/^MailHostUpDown.*/MailHostUpDown = 0/' "$BRO_DIR/etc/broctl.cfg"
    sed -i 's/^MinDiskSpace.*/MinDiskSpace = 0/' "$BRO_DIR/etc/broctl.cfg"
    sed -i 's/^MailConnectionSummary.*/MailConnectionSummary = 0/' "$BRO_DIR/etc/broctl.cfg"
}

reduce_logging() {
    # Logging
    sed -i 's/^LogRotationInterval.*/LogRotationInterval = 600/' "$BRO_DIR/etc/broctl.cfg"
    sed -i 's/^LogExpireInterval.*/LogExpireInterval = 1/' "$BRO_DIR/etc/broctl.cfg"

    # Stats logging
    sed -i 's/^StatsLogEnable.*/StatsLogEnable = 0/' "$BRO_DIR/etc/broctl.cfg"
    # In case we ever decide to enable stats logging I still want it to expire
    sed -i 's/^StatsLogExpireInterval.*/StatsLogExpireInterval = 1/' "$BRO_DIR/etc/broctl.cfg"
}

main() {
    prepare
    install
    setup
}

main
