#!/usr/bin/env bash

set -e
set -x

readonly PACKAGE_NAME=bro
readonly SETUP_DIR=/tmp/setup

prepare() {
    echo "preparing package $PACKAGE_NAME"
    mkdir -p "$SETUP_DIR"
    echo "Installing Dependencies"
    apt-get -y install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev libgeoip-dev
}


#Install the actual package
# https://www.bro.org/sphinx/install/install.html
install() {
    echo "installing package $PACKAGE_NAME"
    cd "$SETUP_DIR"
    git clone --recursive git://git.bro.org/bro
    cd bro
    ./configure
    make
    make install

}

#Configure package
setup() {
    echo "configuring package $PACKAGE_NAME"
    echo "TODO: No configuration put in place at this point."
}

main() {
    prepare
    install
    setup
}

main
