#!/bin/bash

set -e
set -x

readonly SETUP_DIR=/tmp/setup

install_DNS_tools() {
    #Install DNSChef tool
    mkdir -p $SETUP_DIR
    git clone https://github.com/iphelix/dnschef.git "${SETUP_DIR}"/dnschef
    cd "${SETUP_DIR}"/dnschef
    apt-get -y install python-dns
    pip install dnslib
    pip install IPy
    cp dnschef.py /usr/bin/dnschef
}

setup_DNS_tools() {
    #Make our localhost the only nameserver used
    echo "supersede domain-name-servers 127.0.0.1;" >> /etc/dhcp/dhclient.conf
}

main() {
       install_DNS_tools
       setup_DNS_tools
}

main
