#!/usr/bin/env bash

#set +x

readonly IPTABLE_RULE="FORWARD -j NFQUEUE"
readonly SURICATA_CONFIG="/etc/suricata/copilot.conf.yaml"
# Rules not currently used, but kept here if needed
# readonly SURICATA_RULES="/tmp/copilot/copilot-suricata.rules"
#readonly SURICATA_EMPTY="/etc/suricata/copilot_norules.conf"

start_suricata() {
    if [[ -e "$SURICATA_CONFIG" ]]; then
        echo "Starting example configuration"
        iptables -I ${IPTABLE_RULE}
        suricata -q 0 -c "$SURICATA_CONFIG"
    else
        echo "No Rule file found. Not starting Suricata"
        #suricata -c "$SURICATA_EMPTY"
        echo "Ignore the upcoming error message from iptables"
        echo "We didn't create a rule, so it will not be able to delete one."
    fi
}

clean_up() {
    echo "I am cleaning up after myself here."
    iptables -D ${IPTABLE_RULE}
    kill $(< /var/run/suricata.pid)
    exit 0
}


main() {
    start_suricata
}
trap 'clean_up' EXIT
main
