#!/usr/bin/env bash
readonly IPTABLE_TABLE='NFQUEUE'
readonly IPTABLE_RULE="FORWARD -j $IPTABLE_TABLE"
readonly SURICATA_RULES="/tmp/copilot/copilot-suricata.rules"
#readonly SURICATA_EMPTY="/etc/suricata/copilot_norules.conf"

start_suricata() {
    if [[ -e "$SURICATA_RULES" ]]; then
        echo "Starting example configuration"
        iptables -N ${IPTABLE_TABLE}
        iptables -I ${IPTABLE_RULE}
        suricata -q 0 -c "$SURICATA_RULES"
    else
        echo "Not starting Suricata"
        #suricata -c "$SURICATA_EMPTY"
    fi
}

clean_up() {
    echo "I am cleaning up after myself here."
    iptables -D ${IPTABLE_RULE}
    exit 0
}


main() {
    start_suricata
}
trap 'clean_up' EXIT
main
